# Generated by Django 5.0.3 on 2024-08-27 20:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeTrabajo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=10)),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('fechaTermino', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('fechaFinalizado', models.DateTimeField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.IntegerField(blank=True, null=True, unique=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tratos.obra')),
            ],
            options={
                'permissions': [('can_view_informeTrabajo', 'ver InformeTrabajo'), ('can_edit_informeTrabajo', 'editar InformeTrabajo')],
            },
        ),
        migrations.CreateModel(
            name='InformeTrabajo_cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codTalana', models.IntegerField(default=0)),
                ('nomTrab', models.TextField()),
                ('lunTrab', models.BooleanField(default=0)),
                ('marTrab', models.BooleanField(default=0)),
                ('mieTrab', models.BooleanField(default=0)),
                ('jueTrab', models.BooleanField(default=0)),
                ('vieTrab', models.BooleanField(default=0)),
                ('totalDias', models.IntegerField(default=0)),
                ('valorDia', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('itrabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Rebajes.informetrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='InformeTrabajo_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('avance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('itrabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Rebajes.informetrabajo')),
                ('trato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tratos.trato')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tratos.unidadobra')),
            ],
        ),
        migrations.CreateModel(
            name='InformeTrabajo_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=20)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='informetrabajo',
            name='idEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Rebajes.informetrabajo_estado'),
        ),
    ]
