"""
Django settings for TratosPY project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-801(*ud8+yoi6a+o=dh#t&5h7tl^==^29b9y$ir%k!=z+t5elc'
CSRF_TRUSTED_ORIGINS = ['https://*.tratosweb.azurewebsites.net','https://*.127.0.0.1','https://*.tratos.constructoracarran.cl']
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['pruebatratos2.azurewebsites.net']
ALLOWED_HOSTS = ['tratosweb.azurewebsites.net','127.0.0.1','localhost','tratos.constructoracarran.cl']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    #'allauth',
    #'allauth.account',
    #'allauth.socialaccount',
    #'allauth.socialaccount.providers.azuread',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    'django.contrib.humanize',
    #'debug_toolbar',
    'Tratos',
    'Rebajes',
    'Reportes',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Asegúrate de que esté aquí
    #"debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Tratos.middleware.AdminGroupMiddleware',
]

ROOT_URLCONF = 'TratosPY.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TratosPY.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }   
#}

#DATABASES = {
#    'default': {
#        'ENGINE': 'mssql',
#        'NAME': 'TratosObra',
#        'USER': 'desarrollo',
#        'PASSWORD': 'D4de.#@2020',
#        'HOST': '172.18.10.182',  # O la dirección IP de tu servidor SQL
#        'PORT': '',           # El puerto predeterminado de SQL Server es 1433
#        'OPTIONS': {
#            'driver': 'ODBC Driver 17 for SQL Server',  # Asegúrate de que el controlador ODBC esté instalado
#        },
#    }
#}


#POSTGRESQL PROD
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'bdtratos',
        'HOST': 'tratosbd.postgres.database.azure.com',
        'USER': 'usrtratos',
        'PASSWORD': 'Trfgy72q###',
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',
        },
   }
}


#POSTGRESQL TEST
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'bdtratostest',
#        'HOST': 'tratosbd.postgres.database.azure.com',
#        'USER': 'usrtratos',
#        'PASSWORD': 'Trfgy72q###',
#        'PORT': '5432',
#        'OPTIONS': {
#            'sslmode': 'require',
#        },
#   }
#}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = BASE_DIR / "staticfiles"


LOGIN_URL="signin"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
WHITENOISE_MANIFEST_STRICT = False


# Duración de la sesión en segundos (30 minutos)
SESSION_COOKIE_AGE = 1800

# Expirar sesión al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Guardar la sesión en cada solicitud
SESSION_SAVE_EVERY_REQUEST = True



#LOGGING = {
#   'version': 1,
#   'disable_existing_loggers': False,
#   'handlers': {
#      'file': {
#         'level': 'DEBUG',
#         'class': 'logging.FileHandler',
#         'filename': '/temp/debug.log',
#      },
#   },
#   'loggers': {
#      'django': {
#         'handlers': ['file'],
#         'level': 'DEBUG',
#         'propagate': True,
#      },
#   },
#}